---

- name: "ADD/REMOVE NAT RULE"
  panos_nat_rule:
    ip_address: '{{ ansible_host }}'
    username: '{{ username }}'
    password: '{{ password }}'
    rule_name: "{{ item['name'] }}"
    state: "{{ item['state'] | default('present') }}"
    source_zone: "{{ item['source']['zone'] }}"
    destination_zone: "{{ item['destination']['zone'] }}"
    source_ip: "{{ item['source']['network'] }}"
    destination_ip: "{{ item['destination']['network'] }}"
    service: "{{ item['service'] | default(omit) }}"
    snat_type: "{{ item['snat_type'] | default(omit) }}"
    snat_interface_address: "{{ ((item['snat_translation'] | default(omit))['ip']) | default(omit) }}"
    snat_address_type: "{{ item['snat_address_type'] | default(omit) }}"
    snat_interface: "{{ ((item['snat_translation'] | default(omit))['interface']) | default(omit) }}"
    dnat_address: "{{ ((item['dnat_translation'] | default(omit))['ip']) | default(omit) }}"
    dnat_port: "{{ ((item['dnat_translation'] | default(omit))['port']) | default(omit) }}"
  with_items: "{{ cm_nat_rule | list }}"
  #ignore_errors: true
  when: "cm_nat_rule is defined"

- name: "ADD/REMOVE SECURITY RULE"
  panos_security_rule:
    ip_address: '{{ ansible_host }}'
    username: '{{ username }}'
    password: "{{ password }}"
    state: "{{ item['state'] | default('present') }}"
    rule_name: "{{ item['name'] }}"
    rule_type: "{{ item['rule_type'] | default('universal') }}"
    description: "{{ item['description'] | default(omit) }}"
    source_zone: "{{ item['from_zone'] }}"
    destination_zone: "{{ item['to_zone'] }}"
    source_ip: "{{ item['source'] | default(['any']) }}"
    destination_ip: "{{ item['destination'] | default(['any']) }}"
    category: "{{ item['category'] | default(['any']) }}"
    application: "{{ item['application'] }}"
    service: "{{ item['service'] | default(['any']) }}"
    hip_profiles: "{{ item['hip_profiles'] | default(['any']) }}"
    action: "{{ item['action'] | default(['allow']) }}"
    commit: false
  with_items: "{{ cm_security_rule }}"
  when: "cm_security_rule is defined"
