---
- name: "CHECK FOR PREVIOUS STATEFILES"
  stat:
    path: "{{ playbook_dir }}/terraform.tfstate"
  register: statefile

- name: "PROMPT FOR DELETION"
  pause:
    prompt: "Detected previous state file, do you wish to execute against this state? If selecting no, previous state file will be backed up but ignored for this execution. (yes/no)"
  register: state_backup
  when: statefile.stat.exists

- name: "BACKUP FILES"
  include_tasks: "backup-state.yml"
  when: statefile.stat.exists and not state_backup.user_input | bool

- name: "SETUP ENV FOR {{ cloud_provider }}"
  include_tasks: "{{ cloud_provider }}.yml"
