---

- hosts: localhost
  gather_facts: "no"
  connection: local

  vars:
    output_file: 'main-azure.tf'
  vars_files:
    - 'resource_groups.yml'

  tasks:
    - name: Create template
      template:
        src: 'main-azure.tf.j2'
        dest: '{{ output_file }}'

    - name: fmt the things
      command: 'terraform fmt {{ output_file }}'
